#!/usr/bin/env bash
# Configures /etc/hosts so localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8
sed -i 's/127.0.0.1\(.*\)localhost/127.0.0.2\1localhost/' /etc/hosts
if grep -q "facebook.com" /etc/hosts; then
    sed -i 's/.*facebook.com.*/8.8.8.8\tfacebook.com/' /etc/hosts
else
    echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
fi
